# https://github.com/Canop/bacon
wrap = false
[jobs.clippy]
command = ["cargo",
		"clippy",
		"-- fix --"
		"--all-targets",
		"--color",
		"always",
		"-W clippy::pedantic",
		"-W clippy::nursery",
		"-W clippy::expect_used",
		"-W clippy::unwrap_used"]
need_stdout = true
watch = ["tests", "benches", "examples"]
[jobs.exs]
command = ["cargo", "run", "--example", "simple", "--color", "always"]
allow_warnings = true
need_stdout = true
[keybindings]
esc = "back"
ctrl-c = "quit"
q = "quit"
s = "toggle-summary"
w = "toggle-wrap"
t = "toggle-backtrace"
k = "scroll-lines(-1)"
j = "scroll-lines(1)"
